<?php
  include "headandfoot.php";

  print_header();
?>

Git hub test
<ul id="tiles">
  <!-- These are our grid blocks -->
  <li><a href="singlepage.html"><img src="images/g1.jpg" width="275"></a><p>popular <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g2.jpg" width="275"></a><p>reproduced  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g3.jpg" width="275"></a><p>typesetting  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g5.jpg" width="275"></a><p>standard  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g6.jpg" width="275"></a><p>passages <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g7.jpg" width="275"></a><p>containing  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g5.jpg" width="275"></a><p>versions  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g9.jpg" width="275"></a><p>versions  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g10.jpg" width="275"></a><p>established  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g7.jpg" width="275"></a><p>variations  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g12.jpg" width="275"></a><p>random <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g11.jpg" width="275"></a><p>McClintock <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g13.jpg" width="275"></a><p>passage <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g14.jpg" width="275"></a><p>discovered  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g15.jpg" width="275"></a><p>Malorum <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g16.jpg" width="275"></a><p>Bonorum  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g17.jpg" width="275"></a><p>Finibus  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g18.jpg" width="275"></a><p>alteration  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g19.jpg" width="275"></a><p>Internet <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g9.jpg" width="275"></a><p>available <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g10.jpg" width="275"></a><p>infancy <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g7.jpg" width="275"></a><p>words  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g12.jpg" width="275"></a><p>accompanied  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  <li><a href="singlepage.html"><img src="images/g11.jpg" width="275"></a><p>reproduced  <span><a href="singlepage.html"><img src="images/view-icon.png" title="view" /><a href="singlepage.html"><img src="images/like.png" title="like" /><a href="singlepage.html"><img src="images/comment.png" title="link" /></a><a href="singlepage.html"><img src="images/priview.png" title="priview" /></a></span></p></li>
  
  <!-- End of grid blocks -->
</ul>

<?php 
  print_foot();
?>